# Build stage
FROM node:18 as build

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application's code
COPY . .

# Build the application
RUN npm run build

# Production stage
FROM node:18-alpine

WORKDIR /app

# Copy the entire .output directory
COPY --from=build /app/.output ./

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000

# Start the server
CMD ["node", "./server/index.mjs"]