version: '3'
services:

  phoenix:
    image: ${DOCKERHUB_USERNAME}/timemanager-phoenix:prod
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGPORT: 5432
      PGHOST: db
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-}
      MIX_ENV: prod
      PHX_HOST: 46.101.190.248
      PORT: 4000
      POOL_SIZE: 10
      FRONTEND_URL: http://46.101.190.248:3000
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nuxt:
    image: ${DOCKERHUB_USERNAME}/timemanager-nuxt:prod
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      API_URL: http://phoenix:4000/api
      API_BASE_URL: http://46.101.190.248/api
      NUXT_PUBLIC_API_URL: http://46.101.190.248:4000/api
    depends_on:
      - phoenix
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    name: time_manager_pgdata