import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :timemanager, TimemanagerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configure database
config :timemanager, Timemanager.Repo,
       username: System.get_env("PGUSER"),
       password: System.get_env("PGPASSWORD"),
       database: System.get_env("PGDATABASE"),
       hostname: System.get_env("PGHOST"),
       port: String.to_integer(System.get_env("PGPORT") || "5432"),
       pool_size: 10,
       ssl: false

# CORS configuration
config :cors_plug,
       origin: [System.get_env("FRONTEND_URL") || "http://localhost:3000"],
       methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
       headers: ["Authorization", "Content-Type", "Accept", "Origin", "User-Agent", "DNT","Cache-Control", "X-Mx-ReqToken", "Keep-Alive", "X-Requested-With", "If-Modified-Since", "X-CSRF-Token"],
       max_age: 86400,
       credentials: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Timemanager.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
