name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Phoenix image
      uses: docker/build-push-action@v2
      with:
        context: ./api/time_manager
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-phoenix:latest
    
    - name: Build and push Nuxt image
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-nuxt:latest
    
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /path/to/your/project
          docker-compose pull
          docker-compose up -d
