name: Deploy to DigitalOcean via Portainer

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Phoenix image
        uses: docker/build-push-action@v2
        with:
          context: ./api/time_manager
          file: ./api/time_manager/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-phoenix:prod

      - name: Build and push Nuxt image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-nuxt:prod

      - name: Trigger Portainer Webhook
        run: |
          curl -k -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}